package com.team1.codedock.domain.chat.dto;

public enum ChatEventType {
    MESSAGE_CREATED,
    MESSAGE_UPDATED,
    MESSAGE_DELETED,
    THREAD_REPLY_CREATED,
    THREAD_REPLY_UPDATED,
    THREAD_REPLY_DELETED,
    REACTION_UPDATED,
    CHANNEL_READ_STATUS_UPDATED,
    MENTION_DELETED,
    TYPING,
    NOTIFICATION_CREATED
}
